### ISSUE TITLE
Is this SDK support unzipped epub?

### ISSUE THREAD

**Issue by peepo3663** [readium/SDKLauncher-iOS#55] opened 2015-04-17 09:49 UTC
I am developing epub reading system in ios, I had already had unzip process and extract in locally such as EPUB/OPS/... to Document folder
I see only option OpenContainer which work only .epub file. It has another ways to provide this.

**Comment by Twibit** [comment] 2015-04-17 09:55
See https://github.com/readium/readium-sdk/issues/157

**Comment by danielweck** [comment] 2015-04-18 17:18
Out-of-the-box, a Readium SDK "launcher" application serves EPUB contents directly from the zip archive. However, it is possible to create an app that extracts EPUBs to a filesystem location (usually, a secret / obfuscated folder path, possibly storing encrypted files), and to serve those files to the consuming WebViews via the built-in HTTP server. Such application could still use the Readium SDK API to unzip the EPUB contents, so that font de-obfuscation, file decryption, etc. work as intended (see Readium SDK's "Content Filter Chain" feature).
I am closing this issue as I think we answered the question, but of course feel free to re-open, or open a new issue if you feel that is necessary.
Regards, Daniel

**Closed by danielweck** 2015-04-18 17:18 UTC

**Comment by danielweck** [comment] 2015-04-18 17:19
PS: to create such app for iOS, you would need to modify the launcher app code as well as some RDServices code in readium-sdk.
